
import os
import argparse
import glob
import re
import json
import markdown
from github import Github
import google.generativeai as genai

# --- Configuration --- #
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

genai.configure(api_key=GEMINI_API_KEY)

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - SmartGen Docs</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        body {{ background-color: #0f172a; color: #e2e8f0; }}
        .glassmorphism {{ background: rgba(30, 41, 59, 0.7); backdrop-filter: blur(12px); border: 1px solid rgba(255, 255, 255, 0.1); }}
        .prose h1 {{ color: #60a5fa; font-size: 2.25rem; font-weight: 800; margin-bottom: 1.5rem; }}
        .prose h2 {{ color: #9333ea; font-size: 1.5rem; font-weight: 700; margin-top: 2rem; margin-bottom: 1rem; }}
        .prose p {{ margin-bottom: 1rem; line-height: 1.75; }}
        .prose code {{ background-color: #1e293b; padding: 0.2rem 0.4rem; rounded: 0.25rem; font-family: monospace; }}
        .prose pre {{ background-color: #1e293b; padding: 1rem; border-radius: 0.5rem; overflow-x: auto; margin-bottom: 1.5rem; }}
    </style>
</head>
<body class="font-sans antialiased min-h-screen">
    <nav class="glassmorphism p-4 sticky top-0 z-50">
        <div class="container mx-auto flex justify-between items-center">
            <a href="../index.html" class="text-xl font-bold text-blue-400">← Back to Home</a>
            <span class="text-gray-400">{title}</span>
        </div>
    </nav>
    <main class="container mx-auto px-4 py-12 max-w-4xl">
        <article class="glassmorphism p-8 md:p-12 rounded-3xl prose prose-invert lg:prose-xl max-w-none">
            {content}
        </article>
        <div class="mt-12 flex justify-between items-center text-sm text-gray-500">
            <span>Generated by SmartGen Docs AI</span>
            <div class="space-x-4">
                {pagination}
            </div>
        </div>
    </main>
</body>
</html>
"""

def validate_github_url(url):
    pattern = r"https?://github\.com/[\w\.-]+/[\w\.-]+"
    return re.match(pattern, url)

def get_repo_content(repo_full_name):
    g = Github(GITHUB_TOKEN)
    repo = g.get_repo(repo_full_name)
    content = {"readme": "", "package_files": {}, "workflow_files": {}}
    try:
        readme = repo.get_contents("README.md")
        content["readme"] = readme.decoded_content.decode()
    except Exception: pass
    package_file_names = ["package.json", "requirements.txt", "pom.xml", "build.gradle", "go.mod", "Cargo.toml"]
    for file_name in package_file_names:
        try:
            file_content = repo.get_contents(file_name)
            content["package_files"][file_name] = file_content.decoded_content.decode()
        except Exception: pass
    return content

def generate_markdown(model, prompt_template, repo_data):
    prompt = prompt_template.format(repo_data=repo_data)
    response = model.generate_content(prompt)
    return response.text

def create_pagination_html(current_doc, all_docs):
    links = []
    idx = all_docs.index(current_doc)
    if idx > 0:
        prev = all_docs[idx-1]
        links.append(f'<a href="{prev}.html" class="text-blue-400 hover:underline">← Previous: {prev.replace("_", " ").title()}</a>')
    if idx < len(all_docs) - 1:
        nxt = all_docs[idx+1]
        links.append(f'<a href="{nxt}.html" class="text-blue-400 hover:underline">Next: {nxt.replace("_", " ").title()} →</a>')
    return " | ".join(links)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_folder", default="input_links")
    args = parser.parse_args()

    raw_links = []
    files = glob.glob(os.path.join(args.input_folder, "*"))
    for file_path in files:
        if os.path.isfile(file_path) and not file_path.endswith(".gitkeep"):
            with open(file_path, "r") as f:
                content = f.read().strip()
                if content: raw_links.extend(re.split(r'\s+', content))

    valid_links = []
    seen_repos = set()
    for link in raw_links:
        link = link.strip().rstrip("/")
        if validate_github_url(link):
            repo_path = link.split("github.com/")[1].lower()
            if repo_path not in seen_repos:
                valid_links.append(link); seen_repos.add(repo_path)

    if not valid_links: return

    model = genai.GenerativeModel("gemini-3.5-flash")
    os.makedirs("docs", exist_ok=True)

    for repo_link in valid_links:
        repo_full_name = repo_link.split("github.com/")[1].strip("/")
        repo_data = get_repo_content(repo_full_name)

        doc_prompts = {
            "overview": "Generate a unique 'Overview' for this project. Data: {repo_data}",
            "architecture": "Generate an 'Architecture Guide'. Data: {repo_data}",
            "deploy_guide": "Generate a 'Deployment Guide'. Data: {repo_data}",
            "how_to_use": "Generate a 'How to Use' guide. Data: {repo_data}"
        }
        doc_order = ["overview", "architecture", "deploy_guide", "how_to_use"]

        for doc_name in doc_order:
            md_content = generate_markdown(model, doc_prompts[doc_name], repo_data)
            html_content = markdown.markdown(md_content, extensions=['fenced_code', 'tables'])
            pagination = create_pagination_html(doc_name, doc_order)
            
            final_html = HTML_TEMPLATE.format(
                title=doc_name.replace("_", " ").title(),
                content=html_content,
                pagination=pagination
            )
            
            with open(f"docs/{doc_name}.html", "w") as f:
                f.write(final_html)
            # Also save MD for backup
            with open(f"docs/{doc_name}.md", "w") as f:
                f.write(md_content)

if __name__ == "__main__":
    main()
